application: green-grass-811
version: 2
runtime: php
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /static
  static_dir: static

- url: /bower_components
  static_dir: bower_components

